server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://dash-rw-qa.dbc.chenmed.local:3306/DASHBOARD_PROD
    username: lsql_edwing
    password: PBYvPWo0&13
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
